### ISSUE TITLE
Full Fusion 360 Model

### ISSUE THREAD

**Issue by stefanspurgin91** [NikodemBartnik/IndyMill#12]
Hi, i saw that you answered on a few questions about full 3D model, that we can to use some files, but full model has all, linear modules, aluminium profiles, screws and other stuff. Are you consider to share full 3D model only with Patreon supporters starting from lets say package 2(not the cheapest one). It will be very useful for inspections and customization, i want to build your machine. If some people support you on Ptreon+buy your pdf instruction+order your Indy shield, in my opinion, that people maybe deserve to get fully model via mail, or some link to full 3D model with complete machine. Project is now about 3 years old and you arecprobably working on the new one. I dont see why not to share with patreon supporters at least. Best Regards

**Comment by NikodemBartnik** [comment]
There are all the files available in case you want to replicate the machine. You can easily extrude DXF files to the thickness you need and import STEP files of the 3D printed files. Complete 3D assembly is not publicly available
