### ISSUE TITLE
STEP Files?

### ISSUE THREAD

**Issue by GaryFlowers** [NikodemBartnik/IndyMill#2]
Hello, can you upload the machine assembly STEP files here on GIT? I would like to get measurements off the frame and other parts but I don't see any STEP files like the Dremel CNC. 

PS, keep up the awesome work, and thank you for sharing your projects!

**Comment by BearBang7** [comment]
Yes, This is a Open Source Project.
If we have CAD, STEP file it would be awesome for building further upgrades and developments.

**Comment by NikodemBartnik** [comment]
There are STEP files for 3D printed parts and DXF for the plates, based on that you can create your own assembly that will suit your needs
