### ISSUE TITLE
500W Spindle PWM Converter

### ISSUE THREAD

**Issue by MarkedOne** [NikodemBartnik/IndyMill#4]
The text states it's for a 0-10v signal. However in the video and other media, it blows on 0-10v. you changed it in the video for 0-5v, is the silkscreen text incorrect?

**Comment by NikodemBartnik** [comment]
This change is not implemented yet. You need to change one voltage divider to adjust it to different voltage. And you also need to check if you spindle is indeed 0-5V because some of them are controlled with 0-10V.
