### ISSUE TITLE
1.5KW mounting plate

### ISSUE THREAD

**Issue by jack9603301** [NikodemBartnik/IndyMill#5]
Hello, I saw the installation plate of 500W, but I didn't see the installation plate of 1.5KW spindle. Where is it?

**Comment by NikodemBartnik** [comment]
There is too many different version of 1.5kW spindle and it's just not possible to design a single plate that will work with all (or at least most) spindles. As you can see in this video: https://www.youtube.com/watch?v=VLe03TqoPkM
I drilled some additional holes in 500W plate to mount the new spindle. You can also just import the DXF file to any CAD software and easily edit the 500W spindle plate to get it working with your spindle.
