### ISSUE TITLE
Full 3D model?

### ISSUE THREAD

**Issue by eyesonlybob** [NikodemBartnik/IndyMill#6]
Awesome project! I don't see a full 3D model available. Can you add one? I'm interested in building one but want to inspect the assembly closer first.

**Comment by Kosh42** [comment]
What I was after too. To be fully Open Source, the source should also be available to inspect, and adapt. Otherwise free to build is possibly more accurate description.

Still an awesome project. I just want to scale it down for my needs.

**Comment by NikodemBartnik** [comment]
You can find all the STEP files for 3D printed parts and DXF for the plates, based on that you can create your own assembly that will suit your needs and modify whatever you want. That is the source of the project

**Comment by eyesonlybob** [comment]
That just makes things more difficult than it needs to be.  You're limiting
further development of indymill by not releasing the full model.
