### ISSUE TITLE
I have a question. Has the author of indymill considered using LinuxCNC to control this CNC?

### ISSUE THREAD

**Issue by jack9603301** [NikodemBartnik/IndyMill#7]
I have a question. Has the author of indymill considered using LinuxCNC to control this CNC?

It should be better and have strong scalability. Of course, you need SBC or industrial computer for system integration. It looks close to a truly sophisticated device.. Raspberry PI and orange PI offer new possibilities. Of course, it depends on the specific individual who built the CNC (anyway, indymill is just a prototype of mechanical CNC system design. So is the author. I'm just curious.

**Comment by NikodemBartnik** [comment]
I never tried using LinuxCNC, I am quite happy with GRBL on my machine and have no need for that. As you mentioned that's not a part of the IndyMill project, you can use anything you want to control this machine.

**Comment by jack9603301** [comment]
thanks
